export const PRODUCT_LIST_REQIUEST='PRODUCT_LIST_REQIUEST'
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL'

export const PRODUCT_DETAIL_REQIUEST='PRODUCT_DETAIL_REQIUEST'
export const PRODUCT_DETAIL_SUCCESS='PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL='PRODUCT_DATAIL_FAIL'
